### PR TITLE
Fix RBAC api version in helm chart

### PR DESCRIPTION
**Pull request by pipo02mix**
Newer cluster have the version removed

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
:bow:

**Review by T-Kukawka — APPROVED** [review]

**Comment by whites11** [comment]
@zewolfe have you seen this linting error before?

**Comment by T-Kukawka** [comment]
I  think @zewolfe had similar issue with:
```
2022-07-05 12:54:16,093 app_build_suite.build_steps.helm ERROR: Warning: failed to load object from helm/azure-ad-pod-identity-app/templates/mic-exception.yaml: failed to decode: no kind "AzurePodIdentityException" is registered for version "aadpodidentity.k8s.io/v1" in scheme "pkg/runtime/scheme.go:100"
```

**Comment by zewolfe** [comment]
Hey, yeah. I think I got around this by adding `access-to-secrets` to the list of excluded checks by kube-linter. 

```
2022-07-05 12:54:16,535 app_build_suite.build_steps.helm INFO: helm/azure-ad-pod-identity-app/templates/nmi-clusterrolebinding.yaml: (object: <no namespace>/azure-ad-pod-identity-app-nmi rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding) binding to "azure-ad-pod-identity-app-nmi" clusterrole that has [get] access to [secrets] (check: access-to-secrets, remediation: Where possible, remove get, list and watch access to secret objects in the cluster.)
```

**Pull request merged**
