### PR TITLE
Add app icon

### LINKED ISSUE #2: Add app icon
image

### PR DESCRIPTION
**Pull request by marians**
Closes #2

### CODE REVIEW

**Comment by marians** [comment]
I'd appreciate help with the failing CI check here

**Comment by omegas27** [comment]
Could it be a difference between helm 2 and helm 3 handling?

**Comment by marians** [comment]
Thanks for taking this on @omegas27 ! Can you please also do a release? I don't really know whether the change you made here last would make it a patch or any other sort of release.

**Comment by omegas27** [comment]
You are welcome. I created the release v0.2.1 :)

**Pull request merged**
